<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Owner\Controllers\" />
    <Folder Include="Areas\Owner\Views\" />
    <Folder Include="Areas\Shop\Controllers\" />
    <Folder Include="Areas\Shop\Views\" />
    <Folder Include="Areas\Storefront\Controllers\" />
    <Folder Include="Areas\Storefront\Views\" />
  </ItemGroup>

</Project>
